// Package codegen produces a TypeScript surface for the aha MCP tools so
// code-mode runtimes (Cloudflare @cloudflare/codemode, Anthropic
// code-execution-with-MCP, custom sandbox MCP hosts) can call the tools as
// typed functions instead of round-tripping per-call JSON-RPC schemas.
//
// The struct shapes are derived from Go's reflect package so that adding a
// field to e.g. corpus.VerifyReport reaches the TS surface as soon as the
// generator is re-run. The Ref discriminated union is the one special-case:
// it's an interface in Go (each variant has a custom MarshalJSON), so the
// TS shape is written by hand.
package codegen

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/adewale/aha/internal/corpus"
	"github.com/adewale/aha/internal/search"
)

// Generate returns the full TS module bytes. The output is deterministic and
// safe to compare against a checked-in copy.
func Generate() []byte {
	known := map[string]bool{"Ref": true, "MessageRef": true, "SessionRef": true, "ArtifactRef": true}
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString(refUnion)
	for _, e := range []struct {
		name string
		t    reflect.Type
	}{
		{"SearchResult", reflect.TypeOf(search.Result{})},
		{"ReadEntry", reflect.TypeOf(corpus.ReadEntry{})},
		{"VerifyProblem", reflect.TypeOf(corpus.VerifyProblem{})},
		{"VerifyStats", reflect.TypeOf(corpus.VerifyStats{})},
		{"VerifyReport", reflect.TypeOf(corpus.VerifyReport{})},
		{"Conflict", reflect.TypeOf(corpus.Conflict{})},
		{"SizeReport", reflect.TypeOf(corpus.SizeReport{})},
	} {
		writeStructInterface(&b, e.name, e.t, known)
		known[e.name] = true
	}
	b.WriteString(opaqueTypes)
	b.WriteString(argInterfaces)
	b.WriteString(transportAndFactory)
	return b.Bytes()
}

// header carries an explicit @generated marker so GitHub treats the file as
// generated for blame, code search, and PR review. See
// https://github.blog/changelog/2024-10-31-mark-generated-files-in-prs/ for
// the convention.
const header = `// @generated by cmd/aha-gen-ts. DO NOT EDIT.
//
// Typed TypeScript surface for the aha read-only MCP tools. Pass any
// Transport (stdio MCP client, HTTP client against ` + "`aha serve`" + `,
// or a code-mode runtime's tool proxy) to aha() and call tools as
// typed async functions.
//
// To regenerate after changing a Go struct shape:
//   go run ./cmd/aha-gen-ts

`

const refUnion = `export interface MessageRef { kind: "message"; session_key: string; entry_id: string; }
export interface SessionRef { kind: "session"; session_key: string; }
export interface ArtifactRef { kind: "artifact"; artifact_sha256: string; }
export type Ref = MessageRef | SessionRef | ArtifactRef;

`

const opaqueTypes = `// Tools whose Go return type is map[string]any are exposed loosely.
// Callers that need stronger typing can cast at the call site.
export type StatusReport = Record<string, unknown>;
export type DoctorReport = Record<string, unknown>;

`

const argInterfaces = `export interface SearchArgs {
  query: string;
  source?: string;
  machine?: string;
  role?: string;
  after?: string;
  before?: string;
  path?: string;
  path_token?: string;
  project?: string;
  limit?: number;
}

export interface ReadArgs {
  ref?: string;
  session?: string;
  entry?: string;
  before?: number;
  after?: number;
}

`

const transportAndFactory = `// Transport is the abstraction a host supplies. Implementations translate a
// tool name + args object into the underlying MCP tools/call and return the
// parsed JSON payload. Code-mode runtimes already expose this shape; for
// stdio or HTTP, write a tiny adapter.
export interface Transport {
  call(name: string, args: Record<string, unknown>): Promise<unknown>;
}

export function aha(transport: Transport) {
  return {
    search: (args: SearchArgs) =>
      transport.call("search", args as unknown as Record<string, unknown>) as Promise<SearchResult[]>,
    read: (args: ReadArgs) =>
      transport.call("read", args as unknown as Record<string, unknown>) as Promise<ReadEntry[]>,
    status: () => transport.call("status", {}) as Promise<StatusReport>,
    verify: () => transport.call("verify", {}) as Promise<VerifyReport>,
    conflicts: () => transport.call("conflicts", {}) as Promise<Conflict[]>,
    corpus_size: () => transport.call("corpus_size", {}) as Promise<SizeReport>,
    doctor: () => transport.call("doctor", {}) as Promise<DoctorReport>,
  };
}

export const TOOLS = [
  "search",
  "read",
  "status",
  "verify",
  "conflicts",
  "corpus_size",
  "doctor",
] as const;
export type ToolName = (typeof TOOLS)[number];
`

// writeStructInterface emits a TS interface for a Go struct using the JSON
// field tags as property names. Fields are emitted in declaration order so
// the generated file is a deterministic, diff-friendly artifact. Fields
// tagged `json:"-"` are skipped; fields with `,omitempty` become optional.
//
// `known` is the set of interface names already emitted earlier in the file.
// When a struct field references another struct, the generator panics with
// a clear message rather than silently emitting a dangling type reference.
func writeStructInterface(b *bytes.Buffer, name string, t reflect.Type, known map[string]bool) {
	fmt.Fprintf(b, "export interface %s {\n", name)
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		if tag == "-" || tag == "" {
			continue
		}
		parts := strings.Split(tag, ",")
		jsonName := parts[0]
		if jsonName == "" {
			continue
		}
		optional := false
		for _, p := range parts[1:] {
			if p == "omitempty" {
				optional = true
			}
		}
		ts := goTypeToTS(f.Type, f.Name, known)
		q := ""
		if optional {
			q = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", jsonName, q, ts)
	}
	b.WriteString("}\n\n")
}

// goTypeToTS maps a Go reflect.Type to its TS equivalent for the small set of
// shapes the aha surface actually uses.
//
// The mapping is intentionally narrow: any unknown shape panics so the
// generator fails loudly when someone adds a Go type (e.g. time.Time, a new
// interface, a nested struct from another package) without first deciding
// how it should look in TS. Compare to silently emitting "Time" or "unknown"
// and shipping a TS file that misleads code-mode agents.
func goTypeToTS(t reflect.Type, fieldName string, known map[string]bool) string {
	// Special-case the Ref interface field on search.Result: a Go interface
	// has no concrete reflect.Type until runtime, but every variant
	// marshals to a discriminated JSON shape.
	if fieldName == "Ref" {
		return "Ref"
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return goTypeToTS(t.Elem(), "", known) + "[]"
	case reflect.Ptr:
		return goTypeToTS(t.Elem(), fieldName, known)
	case reflect.Map:
		return "Record<string, unknown>"
	case reflect.Struct:
		if t.Name() == "" {
			panic(fmt.Sprintf("codegen: anonymous struct in field %q has no TS equivalent", fieldName))
		}
		if !known[t.Name()] {
			panic(fmt.Sprintf("codegen: field %q references type %q before it is emitted; add it to Generate() above this point", fieldName, t.Name()))
		}
		return t.Name()
	case reflect.Interface:
		panic(fmt.Sprintf("codegen: interface field %q has no concrete TS mapping; add a special case in goTypeToTS", fieldName))
	}
	panic(fmt.Sprintf("codegen: unhandled Go kind %s for field %q", t.Kind(), fieldName))
}
