// Package codegen produces a TypeScript surface for the aha MCP tools so
// code-mode runtimes (Cloudflare @cloudflare/codemode, Anthropic
// code-execution-with-MCP, custom sandbox MCP hosts) can call the tools as
// typed functions instead of round-tripping per-call JSON-RPC schemas.
//
// The struct shapes are derived from Go's reflect package so that adding a
// field to e.g. corpus.VerifyReport reaches the TS surface as soon as the
// generator is re-run. The Ref discriminated union is the one special-case:
// it's an interface in Go (each variant has a custom MarshalJSON), so the
// TS shape is written by hand.
package codegen

import (
	"bytes"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/adewale/aha/internal/corpus"
	"github.com/adewale/aha/internal/search"
)

// Generate returns the full TS module bytes. The output is deterministic and
// safe to compare against a checked-in copy.
func Generate() []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString(refUnion)
	writeStructInterface(&b, "SearchResult", reflect.TypeOf(search.Result{}))
	writeStructInterface(&b, "ReadEntry", reflect.TypeOf(corpus.ReadEntry{}))
	writeStructInterface(&b, "VerifyProblem", reflect.TypeOf(corpus.VerifyProblem{}))
	writeStructInterface(&b, "VerifyStats", reflect.TypeOf(corpus.VerifyStats{}))
	writeStructInterface(&b, "VerifyReport", reflect.TypeOf(corpus.VerifyReport{}))
	writeStructInterface(&b, "Conflict", reflect.TypeOf(corpus.Conflict{}))
	writeStructInterface(&b, "SizeReport", reflect.TypeOf(corpus.SizeReport{}))
	b.WriteString(opaqueTypes)
	b.WriteString(argInterfaces)
	b.WriteString(transportAndFactory)
	return b.Bytes()
}

const header = `// Generated by cmd/aha-gen-ts. DO NOT EDIT.
//
// Typed TypeScript surface for the aha read-only MCP tools. Pass any
// Transport (stdio MCP client, HTTP client against ` + "`aha serve`" + `,
// or a code-mode runtime's tool proxy) to aha() and call tools as
// typed async functions.

`

const refUnion = `export interface MessageRef { kind: "message"; session_key: string; entry_id: string; }
export interface SessionRef { kind: "session"; session_key: string; }
export interface ArtifactRef { kind: "artifact"; artifact_sha256: string; }
export type Ref = MessageRef | SessionRef | ArtifactRef;

`

const opaqueTypes = `// Tools whose Go return type is map[string]any are exposed loosely.
// Callers that need stronger typing can cast at the call site.
export type StatusReport = Record<string, unknown>;
export type DoctorReport = Record<string, unknown>;

`

const argInterfaces = `export interface SearchArgs {
  query: string;
  source?: string;
  machine?: string;
  role?: string;
  after?: string;
  before?: string;
  path?: string;
  path_token?: string;
  project?: string;
  limit?: number;
}

export interface ReadArgs {
  ref?: string;
  session?: string;
  entry?: string;
  before?: number;
  after?: number;
}

`

const transportAndFactory = `// Transport is the abstraction a host supplies. Implementations translate a
// tool name + args object into the underlying MCP tools/call and return the
// parsed JSON payload. Code-mode runtimes already expose this shape; for
// stdio or HTTP, write a tiny adapter.
export interface Transport {
  call(name: string, args: Record<string, unknown>): Promise<unknown>;
}

export function aha(transport: Transport) {
  return {
    search: (args: SearchArgs) =>
      transport.call("search", args as unknown as Record<string, unknown>) as Promise<SearchResult[]>,
    read: (args: ReadArgs) =>
      transport.call("read", args as unknown as Record<string, unknown>) as Promise<ReadEntry[]>,
    status: () => transport.call("status", {}) as Promise<StatusReport>,
    verify: () => transport.call("verify", {}) as Promise<VerifyReport>,
    conflicts: () => transport.call("conflicts", {}) as Promise<Conflict[]>,
    corpus_size: () => transport.call("corpus_size", {}) as Promise<SizeReport>,
    doctor: () => transport.call("doctor", {}) as Promise<DoctorReport>,
  };
}

export const TOOLS = [
  "search",
  "read",
  "status",
  "verify",
  "conflicts",
  "corpus_size",
  "doctor",
] as const;
export type ToolName = (typeof TOOLS)[number];
`

// writeStructInterface emits a TS interface for a Go struct using the JSON
// field tags as property names. Fields tagged with `json:"-"` are skipped;
// fields with `,omitempty` become optional (`name?:`).
func writeStructInterface(b *bytes.Buffer, name string, t reflect.Type) {
	fmt.Fprintf(b, "export interface %s {\n", name)
	type fld struct {
		name     string
		ts       string
		optional bool
	}
	var fields []fld
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		if tag == "-" || tag == "" {
			continue
		}
		parts := strings.Split(tag, ",")
		jsonName := parts[0]
		if jsonName == "" {
			continue
		}
		optional := false
		for _, p := range parts[1:] {
			if p == "omitempty" {
				optional = true
			}
		}
		fields = append(fields, fld{name: jsonName, ts: goTypeToTS(f.Type, f.Name), optional: optional})
	}
	sort.SliceStable(fields, func(i, j int) bool { return false }) // preserve declaration order
	for _, f := range fields {
		q := ""
		if f.optional {
			q = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", f.name, q, f.ts)
	}
	b.WriteString("}\n\n")
}

// goTypeToTS maps a Go reflect.Type to its TS equivalent for the small set of
// shapes the aha surface actually uses. Unknown shapes fall back to `unknown`.
func goTypeToTS(t reflect.Type, fieldName string) string {
	// Special-case: the Ref interface field on search.Result has no concrete
	// reflect.Type until runtime. We pin it as the union by field name.
	if fieldName == "Ref" {
		return "Ref"
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return goTypeToTS(t.Elem(), "") + "[]"
	case reflect.Ptr:
		return goTypeToTS(t.Elem(), fieldName)
	case reflect.Map:
		return "Record<string, unknown>"
	case reflect.Struct:
		// Reference by name; the caller is responsible for emitting the
		// matching interface earlier in the file.
		return t.Name()
	case reflect.Interface:
		return "unknown"
	}
	return "unknown"
}
