// Package codegen produces a TypeScript surface for the aha MCP tools so
// code-mode runtimes (Cloudflare @cloudflare/codemode, Anthropic
// code-execution-with-MCP, custom sandbox MCP hosts) can call the tools as
// typed functions instead of round-tripping per-call JSON-RPC schemas.
//
// The struct shapes are derived from Go's reflect package so that adding a
// field to e.g. corpus.VerifyReport reaches the TS surface as soon as the
// generator is re-run. The Ref discriminated union is the one special-case:
// it's an interface in Go (each variant has a custom MarshalJSON), so the
// TS shape is written by hand.
package codegen

import (
	"bytes"
	"fmt"
	"reflect"
	"runtime/debug"
	"strings"

	"github.com/adewale/aha/internal/corpus"
	"github.com/adewale/aha/internal/mcp"
	"github.com/adewale/aha/internal/search"
)

// fieldExtraDocs carries human-facing detail that can't be inferred from
// a Go type alone: FTS5 query syntax, the meaning of fields whose Go-level
// name doesn't capture user-facing semantics, etc. Keyed by
// "<TSInterfaceName>.<jsonField>".
var fieldExtraDocs = map[string]string{
	"SearchArgs.query":     "Uses SQLite FTS5 syntax: uppercase AND/OR/NOT for boolean, quoted phrases for exact, * for prefix. Lowercase or/and are treated as literal tokens, not operators — `\"fix OR broken\"` matches the literal text, while `\"fix\" OR \"broken\"` is a disjunction.",
	"SearchResult.project": "The source-recorded cwd path of the session (e.g. `/Users/me/proj`), not a logical project name.",
}

// Generate returns the full TS module bytes. The output is deterministic and
// safe to compare against a checked-in copy.
func Generate() []byte {
	known := map[string]bool{"Ref": true, "MessageRef": true, "SessionRef": true, "ArtifactRef": true}
	var b bytes.Buffer
	b.WriteString(makeHeader())
	b.WriteString(refUnion)
	b.WriteString(refHelpers)
	for _, e := range []struct {
		name string
		t    reflect.Type
	}{
		{"SearchResult", reflect.TypeOf(search.Result{})},
		{"ReadEntry", reflect.TypeOf(corpus.ReadEntry{})},
		{"VerifyProblem", reflect.TypeOf(corpus.VerifyProblem{})},
		{"VerifyStats", reflect.TypeOf(corpus.VerifyStats{})},
		{"VerifyReport", reflect.TypeOf(corpus.VerifyReport{})},
		{"Conflict", reflect.TypeOf(corpus.Conflict{})},
		{"SizeReport", reflect.TypeOf(corpus.SizeReport{})},
		{"ResolutionPath", reflect.TypeOf(corpus.ResolutionPath{})},
		{"Incident", reflect.TypeOf(corpus.Incident{})},
		{"TrajectoryStep", reflect.TypeOf(corpus.TrajectoryStep{})},
		{"NamedCount", reflect.TypeOf(corpus.NamedCount{})},
		{"Overview", reflect.TypeOf(corpus.Overview{})},
	} {
		writeStructInterface(&b, e.name, e.t, known)
		known[e.name] = true
	}
	b.WriteString(opaqueTypes)
	b.WriteString(inputInterfaces())
	b.WriteString(transportAndFactory)
	return b.Bytes()
}

// makeHeader returns the file header. The provenance line records the
// generator version (the Go module's main info), so a TS file pulled
// from a tree at some unknown checkout can be traced back to which Go
// codebase emitted it.
func makeHeader() string {
	provenance := "unknown"
	if info, ok := debug.ReadBuildInfo(); ok && info.Main.Path != "" {
		provenance = info.Main.Path
		if info.Main.Version != "" && info.Main.Version != "(devel)" {
			provenance += "@" + info.Main.Version
		}
	}
	return "// @generated by cmd/aha-gen-ts from " + provenance + ". DO NOT EDIT.\n" + `//
// Typed TypeScript surface for the aha read-only MCP tools. Pass any
// Transport (stdio MCP client, HTTP client against ` + "`aha serve`" + `,
// or a code-mode runtime's tool proxy) to aha() and call tools as
// typed async functions.
//
// To regenerate after changing a Go struct shape:
//   go run ./cmd/aha-gen-ts

`
}

const refUnion = `export interface MessageRef { kind: "message"; session_key: string; entry_id: string; }
export interface SessionRef { kind: "session"; session_key: string; }
export interface ArtifactRef { kind: "artifact"; artifact_sha256: string; }
export type Ref = MessageRef | SessionRef | ArtifactRef;

`

// refHelpers carries the parseRef/formatRef pair so TS callers can build
// the canonical ref strings the read tool expects without copying regexes
// from internal/model/ref.go. The wire format is the source of truth.
const refHelpers = `// parseRef accepts the canonical ref strings the search/read tools use
// over the wire ("msg:v1:<base64url(sk)>:<base64url(entry)>", "session:v1:<base64url(sk)>", "artifact:v1:<sha>")
// and returns the typed shape, or null on any malformed input.
export function parseRef(s: string): Ref | null {
  if (typeof s !== "string" || s.length === 0) return null;
  const m = s.match(/^msg:v1:([A-Za-z0-9_-]+):([A-Za-z0-9_-]+)$/);
  if (m) {
    const session = b64urlDecodeText(m[1]);
    const entry = b64urlDecodeText(m[2]);
    return session && entry ? { kind: "message", session_key: session, entry_id: entry } : null;
  }
  const ss = s.match(/^session:v1:([A-Za-z0-9_-]+)$/);
  if (ss) {
    const session = b64urlDecodeText(ss[1]);
    return session ? { kind: "session", session_key: session } : null;
  }
  const a = s.match(/^artifact:v1:([a-f0-9]{64})$/);
  if (a) return { kind: "artifact", artifact_sha256: a[1] };
  return null;
}

// formatRef is the inverse of parseRef. Useful when callers have built a
// Ref value programmatically (e.g. extracting a sha from text) and need to
// pass it to tools.read({ref: ...}).
export function formatRef(ref: Ref): string {
  switch (ref.kind) {
    case "message":  return ["msg", "v1", b64urlEncodeText(ref.session_key), b64urlEncodeText(ref.entry_id)].join(":");
    case "session":  return "session:v1:" + b64urlEncodeText(ref.session_key);
    case "artifact": return "artifact:v1:" + ref.artifact_sha256;
  }
}

function b64urlEncodeText(s: string): string {
  const bytes = new TextEncoder().encode(s);
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}

function b64urlDecodeText(s: string): string | null {
  if (!/^[A-Za-z0-9_-]+$/.test(s)) return null;
  const base64 = s.replaceAll("-", "+").replaceAll("_", "/");
  const padded = base64 + "===".slice((base64.length + 3) % 4);
  try {
    const binary = atob(padded);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    return null;
  }
}

`

const opaqueTypes = `// Tools whose Go return type is map[string]any are exposed loosely.
// Callers that need stronger typing can cast at the call site.
export type StatusReport = Record<string, unknown>;
export type DoctorReport = Record<string, unknown>;

`

// inputInterfaces emits the SearchArgs / ReadArgs TS shapes. SearchArgs
// is derived from the Go SearchInput struct (so jsonschema descriptions
// reach TS as JSDoc); ReadArgs is hand-rolled as a discriminated union
// (Go can't express it natively, but the wire allows only ref XOR
// session+entry meaningfully).
func inputInterfaces() string {
	var b bytes.Buffer
	writeStructInterfaceWithDocs(&b, "SearchArgs", reflect.TypeOf(mcp.SearchInput{}))
	writeStructInterfaceWithDocs(&b, "IncidentsArgs", reflect.TypeOf(mcp.IncidentsInput{}))
	writeStructInterfaceWithDocs(&b, "IncidentTrajectoryArgs", reflect.TypeOf(mcp.IncidentTrajectoryInput{}))
	b.WriteString(readArgsUnion)
	return b.String()
}

const readArgsUnion = `/**
 * ReadArgs is a discriminated union: provide either a canonical ` + "`ref`" + ` OR
 * a ` + "`session`" + ` (plus optional ` + "`entry`" + `), never both. The wire form is the
 * same in either case; the union is documented to push callers toward
 * one mode.
 *
 * The session form also accepts ` + "`mode`" + `: 'window' (default, file-order
 * context around the entry), 'branch' (walk the Pi parent_id tree from the
 * entry leaf to the root), or 'live' (branch plus compaction collapse and
 * non-participating entries filtered). branch/live require ` + "`entry`" + ` as the
 * leaf to walk back from.
 */
export type ReadArgs =
  | {
      /** Canonical wire-format ref text. See parseRef/formatRef for ergonomic construction. */
      ref: string;
      session?: never;
      entry?: never;
      mode?: never;
      before?: number;
      after?: number;
    }
  | {
      /** Session key. Use with optional entry to target a specific message; omit entry for the whole session. */
      session: string;
      ref?: never;
      entry?: string;
      /** Window mode reads file-order context around entry/session. */
      mode?: "window";
      before?: number;
      after?: number;
    }
  | {
      /** Session key for branch/live reconstruction. */
      session: string;
      ref?: never;
      /** Required leaf entry for branch/live reconstruction. */
      entry: string;
      /** Branch/live walk the parent_id tree from this leaf. */
      mode: "branch" | "live";
      before?: number;
      after?: number;
    };

`

// transportAndFactory carries JSDoc on each method derived from
// mcp.ToolDescriptions so a code-mode LLM reading the surface sees the
// same per-tool descriptions it would get over tools/list. Updated at
// regenerate time; the drift test catches descriptions that diverge.
var transportAndFactory = func() string {
	var b strings.Builder
	b.WriteString(`// Transport is the abstraction a host supplies. Implementations translate a
// tool name + args object into the underlying MCP tools/call and return the
// parsed JSON payload. Code-mode runtimes already expose this shape; for
// stdio or HTTP, write a tiny adapter.
export interface Transport {
  call(name: string, args: Record<string, unknown>): Promise<unknown>;
}

export function aha(transport: Transport) {
  return {
`)
	for _, name := range mcp.ToolNames {
		desc := mcp.ToolDescriptions[name]
		fmt.Fprintf(&b, "    /** %s */\n", strings.ReplaceAll(desc, "*/", "* /"))
		switch name {
		case "search":
			b.WriteString(`    search: (args: SearchArgs) =>
      transport.call("search", args as unknown as Record<string, unknown>) as Promise<SearchResult[]>,
`)
		case "read":
			b.WriteString(`    read: (args: ReadArgs) =>
      transport.call("read", args as unknown as Record<string, unknown>) as Promise<ReadEntry[]>,
`)
		case "status":
			b.WriteString(`    status: () => transport.call("status", {}) as Promise<StatusReport>,
`)
		case "verify":
			b.WriteString(`    verify: () => transport.call("verify", {}) as Promise<VerifyReport>,
`)
		case "conflicts":
			b.WriteString(`    conflicts: () => transport.call("conflicts", {}) as Promise<Conflict[]>,
`)
		case "corpus_size":
			b.WriteString(`    corpus_size: () => transport.call("corpus_size", {}) as Promise<SizeReport>,
`)
		case "doctor":
			b.WriteString(`    doctor: () => transport.call("doctor", {}) as Promise<DoctorReport>,
`)
		case "incidents":
			b.WriteString(`    incidents: (args: IncidentsArgs = {}) =>
      transport.call("incidents", args as unknown as Record<string, unknown>) as Promise<Incident[]>,
`)
		case "incident_trajectory":
			b.WriteString(`    incident_trajectory: (args: IncidentTrajectoryArgs) =>
      transport.call("incident_trajectory", args as unknown as Record<string, unknown>) as Promise<TrajectoryStep[]>,
`)
		case "overview":
			b.WriteString(`    overview: () => transport.call("overview", {}) as Promise<Overview>,
`)
		}
	}
	b.WriteString(`  };
}

export const TOOLS = [
`)
	for _, name := range mcp.ToolNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString(`] as const;
export type ToolName = (typeof TOOLS)[number];
`)
	return b.String()
}()

// writeStructInterface emits a TS interface for a Go struct using the JSON
// field tags as property names. Fields are emitted in declaration order so
// the generated file is a deterministic, diff-friendly artifact. Fields
// tagged `json:"-"` are skipped; fields with `,omitempty` become optional.
//
// `known` is the set of interface names already emitted earlier in the file.
// When a struct field references another struct, the generator panics with
// a clear message rather than silently emitting a dangling type reference.
func writeStructInterface(b *bytes.Buffer, name string, t reflect.Type, known map[string]bool) {
	fmt.Fprintf(b, "export interface %s {\n", name)
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		if tag == "-" || tag == "" {
			continue
		}
		parts := strings.Split(tag, ",")
		jsonName := parts[0]
		if jsonName == "" {
			continue
		}
		optional := false
		for _, p := range parts[1:] {
			if p == "omitempty" {
				optional = true
			}
		}
		// Emit JSDoc above the field when we have a description from the
		// jsonschema tag or a hand-curated extra doc for this field.
		schemaDoc := f.Tag.Get("jsonschema")
		extra := fieldExtraDocs[name+"."+jsonName]
		if schemaDoc != "" || extra != "" {
			fmt.Fprintf(b, "  /**\n")
			if schemaDoc != "" {
				fmt.Fprintf(b, "   * %s\n", schemaDoc)
			}
			if extra != "" {
				if schemaDoc != "" {
					fmt.Fprintf(b, "   *\n")
				}
				fmt.Fprintf(b, "   * %s\n", extra)
			}
			fmt.Fprintf(b, "   */\n")
		}
		ts := goTypeToTS(f.Type, f.Name, known)
		q := ""
		if optional {
			q = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", jsonName, q, ts)
	}
	b.WriteString("}\n\n")
}

// writeStructInterfaceWithDocs is the same as writeStructInterface but
// used for input structs. It exists as a separate function so the input
// path can carry slightly different conventions later (e.g. emitting
// `required` lists) without entangling the output-type generator.
func writeStructInterfaceWithDocs(b *bytes.Buffer, name string, t reflect.Type) {
	writeStructInterface(b, name, t, map[string]bool{})
}

// goTypeToTS maps a Go reflect.Type to its TS equivalent for the small set of
// shapes the aha surface actually uses.
//
// Unhandled Go kinds emit `unknown` with a FIXME comment instead of
// panicking. The drift test catches regressions in the regenerated file;
// shipping a `unknown` for a new field is preferable to crashing
// regeneration entirely.
func goTypeToTS(t reflect.Type, fieldName string, known map[string]bool) string {
	// Special-case the Ref interface field on search.Result: a Go interface
	// has no concrete reflect.Type until runtime, but every variant
	// marshals to a discriminated JSON shape.
	if fieldName == "Ref" {
		return "Ref"
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return goTypeToTS(t.Elem(), "", known) + "[]"
	case reflect.Ptr:
		return goTypeToTS(t.Elem(), fieldName, known)
	case reflect.Map:
		return "Record<string, unknown>"
	case reflect.Struct:
		if t.Name() == "" {
			fmt.Fprintf(&warnSink, "codegen: anonymous struct in field %q has no TS equivalent; emitting unknown\n", fieldName)
			return "unknown /* FIXME: anonymous struct */"
		}
		if !known[t.Name()] {
			fmt.Fprintf(&warnSink, "codegen: field %q references type %q before it is emitted; add to Generate() above this point\n", fieldName, t.Name())
			return "unknown /* FIXME: undeclared type " + t.Name() + " */"
		}
		return t.Name()
	case reflect.Interface:
		fmt.Fprintf(&warnSink, "codegen: interface field %q has no concrete TS mapping; emitting unknown\n", fieldName)
		return "unknown /* FIXME: interface type */"
	}
	fmt.Fprintf(&warnSink, "codegen: unhandled Go kind %s for field %q; emitting unknown\n", t.Kind(), fieldName)
	return "unknown /* FIXME: unhandled Go kind " + t.Kind().String() + " */"
}

// warnSink collects codegen warnings. cmd/aha-gen-ts flushes it to stderr
// after Generate() runs so regeneration logs every fallback emitted.
var warnSink bytes.Buffer

// Warnings returns any FIXME-emit warnings collected during the last
// Generate() call. Exported so cmd/aha-gen-ts can surface them to stderr.
func Warnings() string { return warnSink.String() }
