// Generated by cmd/aha-gen-ts. DO NOT EDIT.
//
// Typed TypeScript surface for the aha read-only MCP tools. Pass any
// Transport (stdio MCP client, HTTP client against `aha serve`,
// or a code-mode runtime's tool proxy) to aha() and call tools as
// typed async functions.

export interface MessageRef { kind: "message"; session_key: string; entry_id: string; }
export interface SessionRef { kind: "session"; session_key: string; }
export interface ArtifactRef { kind: "artifact"; artifact_sha256: string; }
export type Ref = MessageRef | SessionRef | ArtifactRef;

export interface SearchResult {
  score: number;
  timestamp: string;
  source: string;
  machine: string;
  project: string;
  role: string;
  snippet: string;
  session_key: string;
  entry_id: string;
  ref: Ref;
  ref_text: string;
}

export interface ReadEntry {
  line_no: number;
  entry_id: string;
  timestamp: string;
  role: string;
  text: string;
  raw_json: string;
}

export interface VerifyProblem {
  code: string;
  message: string;
  count?: number;
}

export interface VerifyStats {
  messages: number;
  artifacts: number;
  fts_messages: number;
  fts_artifacts: number;
  bundles: number;
}

export interface VerifyReport {
  root: string;
  stats: VerifyStats;
  problems?: VerifyProblem[];
}

export interface Conflict {
  id: number;
  session_key: string;
  entry_id: string;
  first_entry_sha256: string;
  second_entry_sha256: string;
  details_json: string;
  created_at: string;
}

export interface SizeReport {
  root: string;
  total_bytes: number;
  database_bytes: number;
  bundle_blob_bytes: number;
  file_blob_bytes: number;
  image_blob_bytes: number;
  other_bytes: number;
  files: number;
}

// Tools whose Go return type is map[string]any are exposed loosely.
// Callers that need stronger typing can cast at the call site.
export type StatusReport = Record<string, unknown>;
export type DoctorReport = Record<string, unknown>;

export interface SearchArgs {
  query: string;
  source?: string;
  machine?: string;
  role?: string;
  after?: string;
  before?: string;
  path?: string;
  path_token?: string;
  project?: string;
  limit?: number;
}

export interface ReadArgs {
  ref?: string;
  session?: string;
  entry?: string;
  before?: number;
  after?: number;
}

// Transport is the abstraction a host supplies. Implementations translate a
// tool name + args object into the underlying MCP tools/call and return the
// parsed JSON payload. Code-mode runtimes already expose this shape; for
// stdio or HTTP, write a tiny adapter.
export interface Transport {
  call(name: string, args: Record<string, unknown>): Promise<unknown>;
}

export function aha(transport: Transport) {
  return {
    search: (args: SearchArgs) =>
      transport.call("search", args as unknown as Record<string, unknown>) as Promise<SearchResult[]>,
    read: (args: ReadArgs) =>
      transport.call("read", args as unknown as Record<string, unknown>) as Promise<ReadEntry[]>,
    status: () => transport.call("status", {}) as Promise<StatusReport>,
    verify: () => transport.call("verify", {}) as Promise<VerifyReport>,
    conflicts: () => transport.call("conflicts", {}) as Promise<Conflict[]>,
    corpus_size: () => transport.call("corpus_size", {}) as Promise<SizeReport>,
    doctor: () => transport.call("doctor", {}) as Promise<DoctorReport>,
  };
}

export const TOOLS = [
  "search",
  "read",
  "status",
  "verify",
  "conflicts",
  "corpus_size",
  "doctor",
] as const;
export type ToolName = (typeof TOOLS)[number];
