// @generated by cmd/aha-gen-ts from github.com/adewale/aha. DO NOT EDIT.
//
// Typed TypeScript surface for the aha read-only MCP tools. Pass any
// Transport (stdio MCP client, HTTP client against `aha serve`,
// or a code-mode runtime's tool proxy) to aha() and call tools as
// typed async functions.
//
// To regenerate after changing a Go struct shape:
//   go run ./cmd/aha-gen-ts

export interface MessageRef { kind: "message"; session_key: string; entry_id: string; }
export interface SessionRef { kind: "session"; session_key: string; }
export interface ArtifactRef { kind: "artifact"; artifact_sha256: string; }
export type Ref = MessageRef | SessionRef | ArtifactRef;

// parseRef accepts the canonical ref strings the search/read tools use
// over the wire ("msg:v1:<sk>:<entry>", "session:v1:<sk>", "artifact:v1:<sha>")
// and returns the typed shape, or null on any malformed input.
export function parseRef(s: string): Ref | null {
  if (typeof s !== "string" || s.length === 0) return null;
  const m = s.match(/^msg:v1:([^:]+):(.+)$/);
  if (m) return { kind: "message", session_key: m[1], entry_id: m[2] };
  const ss = s.match(/^session:v1:([^:]+)$/);
  if (ss) return { kind: "session", session_key: ss[1] };
  const a = s.match(/^artifact:v1:([a-f0-9]{64})$/);
  if (a) return { kind: "artifact", artifact_sha256: a[1] };
  return null;
}

// formatRef is the inverse of parseRef. Useful when callers have built a
// Ref value programmatically (e.g. extracting a sha from text) and need to
// pass it to tools.read({ref: ...}).
export function formatRef(ref: Ref): string {
  switch (ref.kind) {
    case "message":  return `msg:v1:${ref.session_key}:${ref.entry_id}`;
    case "session":  return `session:v1:${ref.session_key}`;
    case "artifact": return `artifact:v1:${ref.artifact_sha256}`;
  }
}

export interface SearchResult {
  score: number;
  timestamp: string;
  source: string;
  machine: string;
  /**
   * The source-recorded cwd path of the session (e.g. `/Users/me/proj`), not a logical project name.
   */
  project: string;
  role: string;
  snippet: string;
  session_key: string;
  entry_id: string;
  ref: Ref;
  ref_text: string;
}

export interface ReadEntry {
  line_no: number;
  entry_id: string;
  timestamp: string;
  role: string;
  text: string;
  raw_json: string;
}

export interface VerifyProblem {
  code: string;
  message: string;
  count?: number;
}

export interface VerifyStats {
  messages: number;
  artifacts: number;
  fts_messages: number;
  fts_artifacts: number;
  bundles: number;
}

export interface VerifyReport {
  root: string;
  stats: VerifyStats;
  problems?: VerifyProblem[];
}

export interface Conflict {
  id: number;
  session_key: string;
  entry_id: string;
  first_entry_sha256: string;
  second_entry_sha256: string;
  details_json: string;
  created_at: string;
}

export interface SizeReport {
  root: string;
  total_bytes: number;
  database_bytes: number;
  bundle_blob_bytes: number;
  file_blob_bytes: number;
  image_blob_bytes: number;
  other_bytes: number;
  files: number;
}

// Tools whose Go return type is map[string]any are exposed loosely.
// Callers that need stronger typing can cast at the call site.
export type StatusReport = Record<string, unknown>;
export type DoctorReport = Record<string, unknown>;

export interface SearchArgs {
  /**
   * Full-text query passed to the corpus FTS index
   *
   * Uses SQLite FTS5 syntax: uppercase AND/OR/NOT for boolean, quoted phrases for exact, * for prefix. Lowercase or/and are treated as literal tokens, not operators — `"fix OR broken"` matches the literal text, while `"fix" OR "broken"` is a disjunction.
   */
  query: string;
  /**
   * Filter by source adapter name (pi, claude-code, codex)
   */
  source?: string;
  /**
   * Filter by machine id
   */
  machine?: string;
  /**
   * Filter by message role (user, assistant, ...)
   */
  role?: string;
  /**
   * RFC3339 lower bound on timestamps
   */
  after?: string;
  /**
   * RFC3339 upper bound on timestamps
   */
  before?: string;
  /**
   * Substring filter against session/artifact paths
   */
  path?: string;
  /**
   * Indexed path-segment filter
   */
  path_token?: string;
  /**
   * Indexed project filter
   */
  project?: string;
  /**
   * Cap on returned hits (default 20, max 200)
   */
  limit?: number;
}

/**
 * ReadArgs is a discriminated union: provide either a canonical `ref` OR
 * a `session` (plus optional `entry`), never both. The wire form is the
 * same in either case; the union is documented to push callers toward
 * one mode.
 *
 * The session form also accepts `mode`: 'window' (default, file-order
 * context around the entry), 'branch' (walk the Pi parent_id tree from the
 * entry leaf to the root), or 'live' (branch plus compaction collapse and
 * non-participating entries filtered). branch/live require `entry` as the
 * leaf to walk back from.
 */
export type ReadArgs =
  | {
      /** Canonical wire-format ref text. See parseRef/formatRef for ergonomic construction. */
      ref: string;
      before?: number;
      after?: number;
    }
  | {
      /** Session key. Use with optional entry to target a specific message; omit entry for the whole session. */
      session: string;
      entry?: string;
      /** Read mode. 'branch'/'live' walk the parent_id tree from the entry leaf; both require entry. */
      mode?: "window" | "branch" | "live";
      before?: number;
      after?: number;
    };

// Transport is the abstraction a host supplies. Implementations translate a
// tool name + args object into the underlying MCP tools/call and return the
// parsed JSON payload. Code-mode runtimes already expose this shape; for
// stdio or HTTP, write a tiny adapter.
export interface Transport {
  call(name: string, args: Record<string, unknown>): Promise<unknown>;
}

export function aha(transport: Transport) {
  return {
    /** Search the corpus over messages and artifacts. Returns ref-bearing results suitable for chaining into read. */
    search: (args: SearchArgs) =>
      transport.call("search", args as unknown as Record<string, unknown>) as Promise<SearchResult[]>,
    /** Retrieve full surrounding context for a search hit. Accepts either a canonical ref text or session+entry coordinates. mode='branch' walks the Pi parent_id tree from the entry leaf to the root; mode='live' adds compaction collapse and filters non-participating entries. */
    read: (args: ReadArgs) =>
      transport.call("read", args as unknown as Record<string, unknown>) as Promise<ReadEntry[]>,
    /** Return corpus health summary: counts and disk usage. */
    status: () => transport.call("status", {}) as Promise<StatusReport>,
    /** Run read-only corpus invariant checks (no repair). */
    verify: () => transport.call("verify", {}) as Promise<VerifyReport>,
    /** List quarantined merge conflicts. */
    conflicts: () => transport.call("conflicts", {}) as Promise<Conflict[]>,
    /** Return corpus on-disk size breakdown. */
    corpus_size: () => transport.call("corpus_size", {}) as Promise<SizeReport>,
    /** Return local environment, config, source, and corpus diagnostics. Depot probing is omitted to keep this tool local-only. */
    doctor: () => transport.call("doctor", {}) as Promise<DoctorReport>,
  };
}

export const TOOLS = [
  "search",
  "read",
  "status",
  "verify",
  "conflicts",
  "corpus_size",
  "doctor",
] as const;
export type ToolName = (typeof TOOLS)[number];
